apiVersion: v1
kind: Service
metadata:
    name: rest-api-service

spec:
    selector:
        app: rest-api
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
          nodePort: 31110
