name: CI

on:
  push:
    branches: [main]
  
  pull_request:
    branches: [main]


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test environment
        run: echo Test environment works
