name: Publish

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./web-api/Dockerfile
          push: true
          tags: muinde/learn-with-geo:latest
          secrets: |
            "PORT=${{ secrets.PORT}}"
            "HOST=${{ secrets.HOST}}"
